**NumPy-Numerical Python**
- Advantages of Numpy Arrays:
  1. Allows several Mathematical Operations
  2. Faster Operations.

In [1]:
import numpy as np

List vs Numpy - Time taken

In [2]:
from time import process_time

Time taken by a lsit

In [5]:
py_li=[i for i in range(10000)]

st_ti=process_time()

py_li=[i+5 for i in py_li]

en_ti=process_time()

print(en_ti - st_ti)

0.0010141910000003307


In [6]:
np_arr=np.array([i for i in range(10000)])

st_ti=process_time()

np_arr += 5

en_ti=process_time()

print(en_ti - st_ti)

0.0009288610000002251


**Numpy Arrays**

In [7]:
## List
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [8]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [10]:
## Creating one dimensional array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [11]:
## Creating two dimensional array
b=np.array([(1,2,3,4,5),(5,6,7,8)])
print(b)

[(1, 2, 3, 4, 5) (5, 6, 7, 8)]


<ipython-input-11-1bd906c282f3>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([(1,2,3,4,5),(5,6,7,8)])


In [12]:
b.shape

(2,)

Initial Placeholders in numpy arrays

In [14]:
## Create a numpy array with zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
## Create a numpy array with ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
## Array of a particular value
z=np.full((5,4),3)
print(z)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [19]:
## Create an identity matrix
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
## Create a numpy array with random values
n=np.random.random((4,4))
print(n)

[[0.01193341 0.04440824 0.74546529 0.62579389]
 [0.94194903 0.91733926 0.18170265 0.68519829]
 [0.80161746 0.79521715 0.05188735 0.60510058]
 [0.72567362 0.70527632 0.3340047  0.45027303]]


In [23]:
## Random integer values array with in a specifi range
rr=np.random.randint(10,100,(4,4))
print(rr)

[[23 74 72 82]
 [37 74 88 45]
 [69 85 87 99]
 [14 72 88 93]]


In [28]:
## Array of evenly spaced values --> Specifying the number of values required.
n=np.arange(10,100,5)
print(n)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [32]:
n=np.arange(3,22,3)
print(n)
type(n)

[ 3  6  9 12 15 18 21]


numpy.ndarray

In [33]:
## Convert a list to a numpy array
l1=[1,2,3,4,5,6]
np_ar=np.asarray(l1)
print(np_ar)
type(np_ar)

[1 2 3 4 5 6]


numpy.ndarray

Analysing a numpy array

In [34]:
a=np.random.randint(10,100,(5,5))
print(a)

[[52 89 91 79 65]
 [25 27 84 73 85]
 [58 38 96 32 42]
 [52 51 66 19 48]
 [76 24 71 89 52]]


In [35]:
## Array dimension
print(a.shape)

(5, 5)


In [36]:
## No of dimensions
print(a.ndim)

2


In [37]:
## No of elements in the array
a.size

25

In [38]:
## Check the data type of the values in the array
a.dtype

dtype('int64')

**Mathematical Operations on a np array**

In [42]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
print(l1+l2) ## Concatenate or joins the two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [40]:
l1.append(l2)

In [41]:
l1

[1, 2, 3, 4, 5, [6, 7, 8, 9, 10]]

In [43]:
l1.extend(l2)
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [45]:
a=np.random.randint(1,10,(4,4))
b=np.random.randint(10,20,(4,4))
print(a)
print(b)

[[8 8 3 7]
 [1 2 5 7]
 [1 1 1 5]
 [8 6 8 7]]
[[14 16 17 11]
 [18 18 14 16]
 [13 12 11 13]
 [16 16 14 19]]


In [46]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[[22 24 20 18]
 [19 20 19 23]
 [14 13 12 18]
 [24 22 22 26]]
[[ -6  -8 -14  -4]
 [-17 -16  -9  -9]
 [-12 -11 -10  -8]
 [ -8 -10  -6 -12]]
[[112 128  51  77]
 [ 18  36  70 112]
 [ 13  12  11  65]
 [128  96 112 133]]
[[0.57142857 0.5        0.17647059 0.63636364]
 [0.05555556 0.11111111 0.35714286 0.4375    ]
 [0.07692308 0.08333333 0.09090909 0.38461538]
 [0.5        0.375      0.57142857 0.36842105]]
[[8 8 3 7]
 [1 2 5 7]
 [1 1 1 5]
 [8 6 8 7]]


In [50]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[22 24 20 18]
 [19 20 19 23]
 [14 13 12 18]
 [24 22 22 26]]
[[ -6  -8 -14  -4]
 [-17 -16  -9  -9]
 [-12 -11 -10  -8]
 [ -8 -10  -6 -12]]
[[112 128  51  77]
 [ 18  36  70 112]
 [ 13  12  11  65]
 [128  96 112 133]]
[[0.57142857 0.5        0.17647059 0.63636364]
 [0.05555556 0.11111111 0.35714286 0.4375    ]
 [0.07692308 0.08333333 0.09090909 0.38461538]
 [0.5        0.375      0.57142857 0.36842105]]


**Array Manipulation**

In [56]:
ar=np.random.randint(0,10,(3,3))
print(ar)

[[7 5 4]
 [3 1 1]
 [8 4 8]]


In [57]:
## Transpose
trans=np.transpose(ar)
print(trans)
print(trans.shape)

[[7 3 8]
 [5 1 4]
 [4 1 8]]
(3, 3)


In [58]:
print(ar)
print(ar.shape)

[[7 5 4]
 [3 1 1]
 [8 4 8]]
(3, 3)


In [59]:
ar1=ar.T
print(ar1)
print(ar1.shape)

[[7 3 8]
 [5 1 4]
 [4 1 8]]
(3, 3)


In [60]:
## Reshaping an array
a=np.random.randint(1,10,(3,2))
print(a)
print(a.shape)

[[4 8]
 [2 1]
 [9 9]]
(3, 2)


In [62]:
b=a.reshape(2,3)
print(b)
print(b.shape)

[[4 8 2]
 [1 9 9]]
(2, 3)
